apiVersion: v1
kind: Service
metadata:
  name: single-sign-on-service
spec:
  type: ClusterIP
  ports:
  - name: single-sign-on-service-port-name
    port: 80
    protocol: TCP
  selector:
    app: SingleSignOn
